[package]
name = "os2_digitalni_potpis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.5"
openssl = "0.10.42"
rand = "0.8.5"
tinyfiledialogs = "3.0"
hex = "0.4.3"
anyhow = "1.0.66"
